### PR TITLE
[#255] On declare return type, simplify FQN automatically

### PR DESCRIPTION
**Pull request by Garethp**
This aims to be a solution to solve #255 by extracting the logic from the `::class can be used instead` inspection in to a utility, and then using that utility in the Return Type Declaration QF.

Progress:

* [x] Extract the ability to check whether the class is imported or not
* [ ] Extract the ability to make the import if needed
* [ ] Use the utility

### CODE REVIEW

**Comment by rentalhost** [comment]
Some news here?

**Comment by rentalhost** [comment]
As we have no news here for about 26 days, then I worked on this issue (except the auto import, but I'll do too) in #320. Hope that you don't feel bad. I'll close this PR for now, but feel free to reopen if you like to improve it in some way.

**Comment by Garethp** [comment]
@rentalhost Really sorry about that, I should have checked in. I had some personal issues come up and didn't have the time to finish this. Thank you for taking care of it, and I'm sorry I didn't post something sooner

**Comment by kalessil** [comment]
No worries @Garethp, hope everything is going well on your side =)

BTW, your Travis integration is super awesome (we are using it already).

**Pull request closed without merging**
