### PR TITLE
[#221] Identify no side-effect statements

### PR DESCRIPTION
**Pull request by rentalhost**
I am implementing the feature request of #221.

**Working in progress: do not merge it yet**

- [x] Update `RULES.md`, `plugin.xml` and _inspection description_;
- [x] Identify no side-effect on know functions (with UT);
- [x] Identify and ignore unknow side-effect on not resolvable functions (with UT);
- [x] Identify possibles side-effects when exists refs on function parameters (with UT);
- [x] Identify external side-effects where function expects a `resource`-type parameter (with UT);
  - [ ] Identify which functions are no side-effect even in this cases (like `imagecolorat()`);
- [x] Identify side-effect on instanced variables, respecting which calls it does (with UT);
  - [ ] Think about how treat field references ($x->) and array assignments;
- [ ] Map all PHP functions that have external side-effects (_have some currently_);
- [ ] Think about how treats `call_func_array()` and `$callable()`, similars;
  - [ ] It includes things like `\ReflectionMethod::invokeArgs()`;
- [ ] Think about how treats _anonymous functions_;
- [ ] `class_exists()` is side-effect only if second parameter is `true`;
- [ ] `header()` is side-effect only more than one parameter is defined;
- [x] Implements supports to `@side-effect` annotation (with UT);
  - [x] Supports only `none`, `possible`, `unknow`, `internal`, `external` (with UT);
  - [x] Inspection for multiple definitions of this annotation (with UT);
  - [x] Inspection for invalid values for this annotation (with UT);
- [ ] Make it works with userland function and methods;
- [ ] _Think about this just now..._

Using [this](https://jsfiddle.net/fh68h40d/) to sort mapped things.

Reviews are welcome anytime.

### CODE REVIEW

**Comment by kalessil** [comment]
Will start review at Monday.

**Comment by rentalhost** [comment]
**WIP Note:** okay, is not too easy to implements that as I think. Although I am making progress, each step that I do I realize that I need do two more. hehe Next weekend I continue on it.

**Comment by kalessil** [comment]
Good progress actually, and no worries - I'm merging PRs as a single commit normally (when no conflicts).

**Comment by kalessil** [comment]
Getting back to this (incl. email) at Tuesday.

**Comment by rentalhost** [comment]
@kalessil You can review it now, but I think that you can wait for a moment to it be at least 90%. Currently I guess that it is about 50%. Is very complex, but I am having some progress!

**Comment by kalessil** [comment]
@rentalhost : ok, I just thought that I still need to answer to your e-mail and do something here.

**Comment by rentalhost** [comment]
@kalessil The email still is welcome! Because is where I am stucked and I think that should have some util that can help me and I hope that you can know what is. Else, I will need implements manually that method.

**Comment by kalessil** [comment]
Ok, then email for now =)

**Comment by rentalhost** [comment]
I'll close it for now, while I am prioritizing milestone, PRs and QFs.

**Comment by kalessil** [comment]
Sounds good to me: can you keep in the current milestone issues you can finish within 2 weeks and re-create PRs for them? This will help to focus on the scope.

**Comment by kalessil** [comment]
Other issues/prs have to wait.

**Pull request closed without merging**
