### PR TITLE
[#300] Missorted modifiers

### PR DESCRIPTION
**Pull request by rentalhost**
Following #300 

This inspection will help sorting the methods modifiers based on [PSR-2: Coding Style Guide](http://www.php-fig.org/psr/psr-2/). 
It declares that:

> [...] `abstract` and `final` MUST be declared before the visibility; `static` MUST be declared after the visibility.

Then it will help ordering the modifiers like:

> [`final` or `abstract`]? [`public `or `protected `or `private`]? [`static`]? `function ()` [...]

---

* [x] Full implementation based on PSR-2 with UTs;
* [x] Support to QF with QFTs;

---

Notes:

1. On the same line is declared too that "_visibility MUST be declared on all properties and methods_". I don't have implemented that because already was implemented on this plugin.
2. Initially I have considered to allow user customize the desired order, but we should follow PSR-2 because it is a standard that is well respected by the community.

### CODE REVIEW

**Comment by kalessil** [comment]
PSR2-based: perfect, perhaps naming could reflect PSR - otherwise, we'll get plenty of reports and requests from teams who not following the PSR.

Enabled by default: I have a very bad feeling about it, can you make it optional, please (partially because of the first note)?

**Comment by kalessil** [comment]
Important! Please reassign milestone tickets to me to where merging is pending.

**Comment by rentalhost** [comment]
Okay, some suggestion to how we should rename? I could think about a option to make static come first (non-PSR). I think that we could use that as default with no problem (user can just disable it or customize).

**Comment by rentalhost** [comment]
What I mean about options: create a radio with two options:

- Visibility before "static" (PSR-2 compliance) (default) 
- Visibility after "static"

**Comment by kalessil** [comment]
Naming: what about "PSR-compliant modifiers order"? Does it sound good enough?
No option are needed, as with `{}` people need to follow PSR or just disable the inspection.

**Comment by rentalhost** [comment]
Seems good for me. I will work on this when I come to home.

**Comment by rentalhost** [comment]
Fixed.

**Comment by kalessil** [comment]
@rentalhost: probably this one?

**Comment by kalessil** [comment]
Thank you @rentalhost !

**Comment by rentalhost** [comment]
Great! Seems that the next release will have a lot of good things. :D

**Comment by kalessil** [comment]
Yep, I had to make preview-release as it big one =)

**Pull request merged**
