### PR TITLE
Initial gh-pages

### LINKED ISSUE #285: GitHub pages for docs ?
What do you think guys of using this feature from GitHub ?

https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

### PR DESCRIPTION
**Pull request by davidmpaz**
After merging this, you need to enable github pages in project: https://pages.github.com/

Afterward it is only about updating doumentation (docs directory) in master, rebasing `gh-pages`  branch to master and pushing `gh-pages` branch.

All of previous paragraph, I believe could be automatized. After @Garethp make the contribution of travis we can deploy also gh-pages automatically. We need to look but travis even have some mechanism to deploy to gh pages. In ultimate case it is about executing some git comands on some of the travis execution states.

Let me know how it went :)

This should close #285

### CODE REVIEW

**Comment by kalessil** [comment]
@davidmpaz : would you also add our GA code (UA-16483983-8)?

**Comment by davidmpaz** [comment]
@kalessil; Sorry, how can I add that ? And where ?

**Comment by kalessil** [comment]
`{% if site.google_analytics %}`, I guess it's a property probably like which layout to use

**Comment by kalessil** [comment]
Thank you @davidmpaz

**Comment by davidmpaz** [comment]
np. Did not got at first the GA thing was Analitics :)

**Pull request merged**
