### PR TITLE
[#423] Added Laravel debug helpers on ForgottenDebugOutputInspector

### PR DESCRIPTION
**Pull request by rentalhost**
Was added `dd()` and `dump()`.

PS. I did a code style update (add `final`, weaking types, sorting methods, so on).

### CODE REVIEW

**Comment by kalessil** [comment]
I picked up the essential changes for 2.3.9, refactoring part under review.

**Comment by rentalhost** [comment]
It was not a refactoring, on really. It was just methods sorting, code spacement (before ifs), applying final modifier. Just one place I did a change based on Java inspection, where the null check was not need (not changed the behaviour). It make the code clear to next events.

**Comment by kalessil** [comment]
@rentalhost : no worries, looks good overall - I was in hurry and my message seems to be misleading. Sorry.

**Comment by rentalhost** [comment]
No problem! Just to clarify.

**Comment by kalessil** [comment]
`dd` was added, I'll skip the rest of changes to ensure release stability. Sorry.

**Pull request closed without merging**
