### PR TITLE
Add multiple issue templates

### PR DESCRIPTION
**Pull request by funivan**

### CODE REVIEW

**Comment by funivan** [comment]
Hey @kalessil . The user can select a specific template before creating an issue.  Look at the symfony repository. This PR can improve user experience. 
screenshot from 2019-02-17 11-03-20

**Comment by andreasschroth** [comment]
Nice, never saw this before. I like this idea!

**Comment by kalessil** [comment]
Before merging, what `<!-- ... -->` is doing exactly?

**Comment by funivan** [comment]
Text inside `<!-- -->` should not be visible in the rendered markup.

**Comment by kalessil** [comment]
Thank you @funivan

**Pull request merged**
