### PR TITLE
[#559] ForgottenDebugOutputInspector: more debug functions (XDebug)

### PR DESCRIPTION
**Pull request by lurkie**
Here you are. After building it, I was able to test it in PHPstorm successfully

### CODE REVIEW

**Comment by kalessil** [comment]
Cool, did you use our dev-docs or something else?

**Comment by kalessil** [comment]
Thank you @lurkie

**Comment by lurkie** [comment]
> Cool, did you use our dev-docs or something else?

Yes. I installed IntelliJ IDEA (community), read the docs on how to set up the project, ran Build Project, and found a JAR file.
It took some carefull reading, but was not hard with the instructions. Thanks for that :+1:

**Comment by kalessil** [comment]
All kudos to @davidmpaz and @rentalhost =)

**Pull request merged**
