### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by kalessil**

### CODE REVIEW

**Comment by kalessil** [comment]
@Garethp, do you need those changes in PhpInspectionsEA.iml.dist and .idea/libraries/lib.xml ?

**Comment by kalessil** [comment]
Closing - had to merge manually to save original contributions

**Comment by rentalhost** [comment]
What mean the "allow_failures"? 
Why it doesn't declare the `jdk` version?

**Comment by kalessil** [comment]
That's way to define matrix build in travis: we use same jdk to build/run test, so env-variables are identifying the build. Allow failures references to eap-build via its' env-variables definition..

**Pull request closed without merging**
