### PR TITLE
[#288] ComparisonOperandsOrderInspector: avoid double-disabling

### PR DESCRIPTION
**Pull request by rentalhost**
Following #288 and #283 

---

(CC) ..., we should avoid the double-disabling of "_Yoda/regular conditions style usage_" (currently you could enable the inspection, but _disable the inspection_ that it does by unchecking both available options). 

* [x] By default, the inspection will be disabled by default;
* [x] ~When enabled, the Yoda style will be checked automatically;~
  * [x] Default option is now "regular style" (https://github.com/kalessil/phpinspectionsea/issues/288#issuecomment-298844018);
* [x] The checkbox should be replaced by radio;
* [x] Rebased to head;
* [x] Conflict resolved;

### CODE REVIEW

**Comment by kalessil** [comment]
@rentalhost : I did change the options component, can you rebase this PR on master, please?

**Comment by kalessil** [comment]
PS: this to be merged next.

**Comment by rentalhost** [comment]
Closing: I have bugged github haha... I reopened on #337

**Comment by kalessil** [comment]
Ahah , what have you done to pity github?

**Comment by rentalhost** [comment]
Instead to rebase the local branch to head, I moved it. Then I pushed to remote (here is the magic!). For some reason the git loses the reference, and even after I fixed it, it just gone. Haha

**Comment by kalessil** [comment]
Muhahah I would admit =)

**Pull request closed without merging**
