### PR TITLE
[#146] References by "new self" instead of "new MyClass"

### LINKED ISSUE #146: References by "new self" instead of "new OwnClass"
Basically, if you references the own class name instead of static or self, your should be warning. It's useful to code reuse because you don't need to change class names to new one.

```php
class OwnClass {
    public function create() {
        // Warning: you should use "new self" here.
        return new OwnClass;
    }
}
```

I am really impresed because it was not suggested or implemented before. Maybe have some reason?

**Edit**: as quoted by @funivan, the unique option is `new self`, because `new static` should changes the code behaviour.

### PR DESCRIPTION
**Pull request by rentalhost**
It fixes #146 

* [x] Replacements (default mode):
  * [x] Replacement from `new MyClass` to `new self`;
  * [x] Replacement from `MyClass::CONSTANT` to `self::CONSTANT`;
  * [x] Replacement from `MyClass::staticMethod()` to `self::staticMethod()`;
  * [x] Replacement from `MyClass::$staticProperty` to `self::$staticProperty`;
  * [x] Replacement from `MyClass::class` to `__CLASS__`;
  * [x] Replacement from `self::class` to `__CLASS__`;
* [x] Options:
  * [x] Reserve way mode ("_prefer class name referencing_");
    * [x] Replacements (with this option enabled):
      * [x] Replacement from `new self` to `new MyClass`;
      * [x] Replacement from `self::CONSTANT` to `MyClass::CONSTANT`;
      * [x] Replacement from `self::staticMethod()` to `MyClass::staticMethod()`;
      * [x] Replacement from `self::$staticProperty` to `MyClass::$staticProperty`;
      * [x] Replacement from `__CLASS__` to `MyClass::class`;
* [x] Tests:
  * [x] Tested for false-positive on a long project (about 10.000 found cases);
  * [x] Tests implemented for both ways (default and reverse);
  * [x] Quick-fix and tests implemented for both ways;
* [ ] Text review (_need help here_);

@funivan is copyrighted because of his helpful comments;

### CODE REVIEW

**Comment by rentalhost** [comment]
One of tests is failing on Travis, on 2017.1. I have installed it locally and runned the tests manually and via junit, and I got no error. Some clue?

**Comment by kalessil** [comment]
Looks like  self-class-referencing.reverse.php getting anonymous classes inspected.

Try with this code for checking if class is anonymous:
```java
final bool isAnonymous = NamedElementUtil.getNameIdentifier(clazz) == null;
```

**Comment by rentalhost** [comment]
No luck. :(

**Comment by rentalhost** [comment]
Okay, I did an additional check up and now it works fine. :)

**Comment by kalessil** [comment]
Thank you @rentalhost !

I'll be test driving it this week, so as usually some adjustment might take place =)

**Pull request merged**
