### PR TITLE
Implement efferent coupling inspection

### PR DESCRIPTION
**Pull request by funivan**
Use this inspection in the project. So I decided to share it with the community.
One thing that I want to implement before merge - edit relations num.
Do not know how to do this with new style of `createOptionsPanel`. 
If this inspection is useful i can continue to work on it.

### CODE REVIEW

**Comment by rentalhost** [comment]
Currently the `OptionsComponent` doesn't supports `number input`, but we can implements that. I will try do something now.

**Comment by funivan** [comment]
@rentalhost many thanks ;)

**Comment by rentalhost** [comment]
Oh, sorry... I broked something on my IDE... I am getting a lot of errors like:
- Unregistered inspections requested
- File accessed outside allowed roots
- display name should be overridden or configured via XML class

And I don't know how I can fix that. Some tips @kalessil?

**Comment by kalessil** [comment]
@rentalhost : check the project structure: File -> Project Structure, perhaps something broken there

**Comment by kalessil** [comment]
It's a good one, the default 20 is empiric or default from the phpdepend?

**Comment by funivan** [comment]
@kalessil 20 is empiric. I will investigate phpdepend and find what is the default value.

**Comment by funivan** [comment]
PhpDepent just show us code metric without any violations. 

PhpMetric use number `20` 
https://github.com/phpmetrics/PhpMetrics/blob/4f4372cbbee8c61f24281d34973d87f66c0185a7/src/Hal/Violation/Class_/TooDependent.php#L31

**Comment by kalessil** [comment]
Awesome, thanks for checking @funivan !

**Comment by kalessil** [comment]
@rentalhost : any news?

**Comment by rentalhost** [comment]
No news. On reality I have not tried anymore. But on a personal project I have no issues (and I have setup on the same way). I am should forgiving something. I will try again on next hours.

**Comment by rentalhost** [comment]
@kalessil Okay, some news here, but nothing good. I reconfigured all project structure as from docs, and I still having some errors. All tests pass, except by one:

> com.kalessil.phpStorm.phpInspectionsEA.**UnqualifiedReferenceInspectorTest**#testFindsAllNonNsPatterns

I am getting:

> java.lang.AssertionError: **File accessed outside allowed roots:** _file://C:/Program Files/JetBrains/PhpStorm/plugins/php/lib/php.jar_;
Allowed roots: [/etc, C:/Temp/unitTest_findsAllNonNsPatterns/com.kalessil.phpStorm.phpInspectionsEA.UnqualifiedReferenceInspectorTest.testFindsAllNonNsPatterns, /private/etc, C:/Users/david, D:/PHP/david/phpinspectionsea/out, C:/Temp/, C:/Program Files/JetBrains/IntelliJ IDEA, C:/Program Files/Java/jdk1.8.0_131/jre, C:/Temp, C:/Users/david/.IntelliJIdea2017.2/system/plugins-sandbox/test]

But, is not only that... 

When I run all tests the "com.kalessil.phpStorm.phpInspectionsEA.codeStyle.**EfferentObjectCouplingInspectorTest**#testFalsePositives" is green, but if I just run only it, it fails with the same error from another class.

And for finish, my another project I have no problem, with the same settings. I don't know what I should do. Some suggestions? I will keep trying here, but I really don't know what do now. 😞 

Maybe reinstall all, clone repository again to local, etc.

Take a look: https://youtu.be/mNlqUBYBQxk

**Comment by kalessil** [comment]
Looking into this

**Comment by funivan** [comment]
@kalessil I can try to write configuration panel in standard manner.

**Comment by kalessil** [comment]
What will be the best option: implement/refactor or clean implementation?

**Comment by funivan** [comment]
Clean implementation will be better.

**Comment by dryabov** [comment]
But, please, don't hardcode COUPLING_LIMIT value. And there should be a way to disable this inspection for some classes (e.g. active records).

**Comment by funivan** [comment]
@dryabov don`t worry.
1. We try to implement configuration panel. You will be able to change `coupling limit`
2. You can disable this inspection for specific scope or suppress for some classes.

**Comment by kalessil** [comment]
@rentalhost, does your test configuration looks similar?

image

**Comment by rentalhost** [comment]
@kalessil Same here...

setup1
setup2

**Comment by kalessil** [comment]
On the last screen (Run/debug configuration): try removing `-ea` from VM options, will this work?

**Comment by rentalhost** [comment]
@kalessil Still without luck... I always receives a "random error". On this time, I am receiving that:

> java.lang.NullPointerException
	at com.kalessil.phpStorm.phpInspectionsEA.EAApplicationComponent.initComponent(EAApplicationComponent.java:28)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:475)
...

Then if I "fix" this part, I receive that:

> java.lang.RuntimeException: java.lang.NullPointerException
	at com.intellij.openapi.ui.TestDialog$1.show(TestDialog.java:23)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:276)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:301)
...

**Comment by kalessil** [comment]
I'm running out f ideas, but perhaps the issue about 2 plugin resources conflict.
Can yo cleanup folder: `C:\Users\Vladimir\.IntelliJIdea2016.2\system\plugins-sandbox\plugins` (use your env-specific user and idea folder) and try running all tests without the `-ea` flag?

**Comment by rentalhost** [comment]
I already have tried it... on reality, I deleted all `plugin-sandbox` folder and get nothing (with/out -ea). I am using now the Community edition (trial expired 😢), but I don't think if it is the problem, because before that I still have the same problem. The unique "difficulty" on community edition is the "CSS plugin" that I copied from PhpStorm (and seems to be working).

I tried to debug this error, but I do not found nothing that could help.

**Comment by kalessil** [comment]
No more ideas, I'll check with JB for one more license for you (hopefully this will help).

**Comment by rentalhost** [comment]
Thanks. Om this case I will try reinstall again and not EAP anymore (it was not the problem, but reduce the risk).

**Comment by kalessil** [comment]
Sounds god, meanwhile I requested an additional license for you

**Comment by kalessil** [comment]
@rentalhost : you should receive an email with the license details

**Comment by rentalhost** [comment]
Thanks! I will keep trying to run it.

**Comment by rentalhost** [comment]
Okay, it works. I don't know exactly what I did to fix that, but I reinstall everything and I copied the PhpStorm dependencies (like `/lib` and `phpstorm.jar`) to inside the IDEA folder (because it is considered an allowed root, which fix some problems).

Now I can back to work hehe

**Comment by rentalhost** [comment]
Oh, forget... seems that git did the job automatically! haha

**Comment by funivan** [comment]
@rentalhost yep, github is great. Thanks for the implementation.
@kalessil your turn.

**Comment by kalessil** [comment]
@funivan : are changes from @rentalhost already here?

**Comment by funivan** [comment]
@kalessil  yep. https://github.com/kalessil/phpinspectionsea/pull/343/commits

**Comment by kalessil** [comment]
Ths, will proceed with the PR

**Comment by funivan** [comment]
Hello. Any news on this PR ?

**Comment by kalessil** [comment]
Hi, yep: I plan the PR for 2.3.8-final (will merge as it comes to preparing the release)

**Comment by kalessil** [comment]
Thank you @funivan and @rentalhost !

**Pull request merged**
