### PR TITLE
Starting a setup of Travis

### PR DESCRIPTION
**Pull request by Garethp**
I thought it might be useful to have an Automated system run the Unit Tests automatically for new PR's and such, so that it's easier to show and share test failures (As well as to set it up to test against multiple versions of IDE's). That being said, there seems to be an issue or two that I can't quite seem to figure out what's going on. I wanted to see if you had any ideas on how to approach it.

To run the tests locally, check out the branch and run `PHPSTORM_ENV="2017.1" ./travis.sh`. To run it on Travis, set this repository up on Travis and have it only run builds when there's a `travis.yml` file

### CODE REVIEW

**Comment by kalessil** [comment]
This would be really great to have!

**Comment by Garethp** [comment]
I don't suppose you have any experience with ant/junit? At the moment I'm running in to a problem where a test throws an error on Travis, but ant just says that the fork exited abnormally with an error, not showing the stacktrace

**Comment by Garethp** [comment]
Nevermind, I sorted it out. [This](https://travis-ci.org/Garethp/phpinspectionsea/builds/216702532) is the current status I have at the moment. I'm investigating ways to bring the output down

**Comment by Garethp** [comment]
FYI: Running the complete test suite on my local IntelliJ, the failures that I'm getting pretty closely match the failures of Travis

**Comment by kalessil** [comment]
Wow, awesome @Garethp. I'll get thru errors to check what happens.

**Comment by Garethp** [comment]
If you find the errors match what you get locally as well, then once this is merged in I'll make PR's for each one. Being able to refer to Travis will make it easy to know which ones to go and fix

**Comment by Haehnchen** [comment]
fyi: Instead of copy my crazy Travis script, another pattern would be to use gradle :):

- https://github.com/artspb/1d34-3v4l-pl4g1n (PhpStorm Team)
- https://github.com/cvette/intellij-neos

**Comment by kalessil** [comment]
@Garethp : master is green again, failing test has been fixed. What do we do next here?

**Comment by Garethp** [comment]
@Haehnchen Thanks for providing the Travis Script in the first place. Gradle might be another option, but through this I got a rough understanding of how your script and ant works. 

Quick question, how are you getting and holding the old versions of IntelliJ? Did you just happen to download them somewhere, and now have them sitting on a server, or do you have a source?

**Comment by Garethp** [comment]
@kalessil I've updated my fork from your base repository (as you can see by the history), and Travis is now [passing](https://travis-ci.org/Garethp/phpinspectionsea/builds/219599424). So, next step is to merge this, create a Travis account and tell travis to watch this repository! You can then add a badge to the `README.md` to tell you if the builds on master are failing, but it should also check all incoming PR's and tell you in the PR if the PR breaks any tests or not

**Comment by Garethp** [comment]
@kalessil I've done a rebase of my branch, it's no longer conflicting and should be mergable

**Comment by kalessil** [comment]
@Garethp : thanks for rebasing, will merge today.

**Comment by Garethp** [comment]
@kalessil If you add me a colaborator, I should be able to set up the Travis for you as well, if you want. And btw, do you want a little build passing badge on the `README.md` file, or is it okay to just have it checking PR's

**Comment by kalessil** [comment]
Let me merge first in separate feature branch, then I'll handover travis/badge to your hands - just a little bit of patience please - promise to finish my part untill Monday.

**Comment by kalessil** [comment]
Thank you @Garethp

**Pull request merged**
